# Simple workflow for deploying static content to GitHub Pages
name: Build and deploy to GH Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Detect Flutter version
      uses: kuhnroyal/flutter-fvm-config-action@v1

    - name: Setup Flutter
      uses: hrishikesh-kadam/setup-flutter@v1
      with:
        ref: ${{ env.FLUTTER_VERSION }}
        setFlutterRootPath: 'true'
        addPubCacheBinToPath: 'true'
        flutterPrecache: '--linux'
    
    - name: Flutter version
      run: flutter --version

    - name: Enable Flutter web
      run: flutter config --enable-web

    - name: Install dependencies
      run: flutter packages get
      
    - name: Run code generation
      run: flutter pub run build_runner build --delete-conflicting-outputs
      
    - name: Flutter analyze
      run: flutter analyze

    - name: Build web
      run: flutter build web --release --base-href '/devtools/'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
